# Generated by Django 5.1 on 2024-08-21 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bookmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('writter', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='Media/book_img')),
                ('published_date', models.DateField()),
                ('type', models.CharField(max_length=100)),
            ],
        ),
    ]
